title: LuiCat's Blog
description: Do you remember how many blogs you have viewed in your life?
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"