title: LuiCat's Blog
description: Greetings.
show_downloads: false
# google_analytics: UA-111000956-1
theme: jekyll-theme-dinky
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
